version: '3.8'
name: chat

services:
  app:
    container_name: chat_app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  db:
    container_name: chat_db
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - "5431:5432"
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    container_name: chat_redis
    image: redis:latest
    env_file: .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
volumes:
  db:
    name: chat_db
  redis_data:
    name: chat_redis