version: '3.8'
name: chat

services:
  db:
    container_name: chat_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: chat_admin
      POSTGRES_PASSWORD: password
    ports:
      - "6543:5432"
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always

    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  db:
    name: chatDb
  redis_data:
    name: chatRedis