version: '3.8'
name: chat

services:
  app:
    container_name: go_chat
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  db:
    container_name: chat_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: chat_admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  db:
    name: chat_db
  redis_data:
    name: chat_redis